[provider]
cluster = "devnet" ## this should also mirror the solana config env
wallet = "~/.config/solana/uxd.json"

[programs.localnet]
controller = "7DrEQkCjDsmiPpZW6LXugtJFz4Sd3zjsXEuum3uQS5Rj"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 100000 tests/test_*.ts"
 