[provider]
cluster = "devnet" ## this should also mirror the solana config env
wallet = "~/.config/solana/id.json"

[programs.localnet]
controller = "Cx1TEt85BEbdaRrBQKrwApi4N9qGxN1Ja5NkmpSEt2v2"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 100000 tests/test_*.ts"
