[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
controller = "UXDConWDuVXUBeDYR5k4PW3nB4MScJ6eKDYqmtZjtAd"
depository = "UXDDepTysvnvAhFyY7tfG793iQAJA8T4ZpyAZyrCLQ7"
oracle = "UXDGB2YeFbSL72cAxYtfQCQXzyyWW2xYPCJ1uSPtNiP"

[programs.devnet]
oracle = "UXDGB2YeFbSL72cAxYtfQCQXzyyWW2xYPCJ1uSPtNiP"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
## cluster can be specified with --provider.cluster <devnet|testnet|localnet>
## value can be accessed through env using `$ANCHOR_PROVIDER_URL`
#test = "./scripts/test.sh"
## When tests are rewritten, we can use this instead
test = "npx ts-mocha -p ./tsconfig.json -t 100000 tests/test_*.ts"
