[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
uxd = "UXD8m9cvwk4RcSxnX2HZ9VudQCEeDH6fRnB4CAP57Dr"

[programs.devnet]
uxd = "4jv7rFE2DJ7HXDtJ812xLLnugXjPTU4iSpBUq8Dm6uEM"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
# Run all tests
# test = "yarn ts-mocha -p ./tsconfig.json -t 500000 tests/test_*.ts"

# Integration tests for SOL collateral
test = "yarn ts-mocha -p ./tsconfig.json -t 500000 tests/test_integration_sol.ts"

# Integration tests for BTC collateral only
# test = "yarn ts-mocha -p ./tsconfig.json -t 500000 tests/test_integration_btc.ts"

## UTILS - fragment of logic for testing during development

# Setup a Controller + Depository (SOL) and deposit 100 USDC insurance
# test = "yarn ts-mocha -p ./tsconfig.json -t 500000 tests/util_setup_controller_depository_sol.ts"

# Mint and Redeem tests for SOL collateral
# test = "yarn ts-mocha -p ./tsconfig.json -t 500000 tests/util_mint_redeem_sol.ts"