[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
uxd = "HTP8ZHRKEANYbJ9nZqoGNDihPdrAdyEiKg8yyzvPae7j"

[programs.mainnet]
uxd = "HTP8ZHRKEANYbJ9nZqoGNDihPdrAdyEiKg8yyzvPae7j"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 50000 tests/test_*.ts"
 