[provider]
cluster = "devnet" ## this should also mirror the solana config env
wallet = "~/.config/solana/id.json"

[programs.localnet]
controller = "BsKg2e15bH65A7JyNRQz5croiQZHAZV4b9vKsf7YeUew"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 100000 tests/test_*.ts"
