[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
uxd = "2iX8NM3dAyx3nhE89WfU6XZjYXFsSuLjqceyequCDn9i"

[programs.mainnet]
uxd = "2iX8NM3dAyx3nhE89WfU6XZjYXFsSuLjqceyequCDn9i"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 50000 tests/test_*.ts"
 