[provider]
cluster = "devnet" ## this should also mirror the solana config env
wallet = "~/.config/solana/id.json"

[programs.localnet]
controller = "3BXK1imSNy3ep3yRJxd3umAF3HmC6SC6XjScfoJamvaZ"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 100000 tests/test_*.ts"
 