[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
controller = "2PCPrsHdeZq6CsHyqnu3NVMcWtJGjZE8mWKpF6ipTDT4"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 100000 tests/test_*.ts"
