[provider]
cluster = "devnet" ## this should also mirror the solana config env
wallet = "~/.config/solana/id.json"

[programs.localnet]
controller = "137dXnDWhuEqfSbJGrWSbaKxcDE3sk8A8V8ze5LTb9TX"
depository = "Feo4PLuC3PB33zj2uU4zZA4dpCRwX7KipB7dHKf83o7d"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 100000 tests/test_*.ts"
