[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
uxd = "UXD8m9cvwk4RcSxnX2HZ9VudQCEeDH6fRnB4CAP57Dr"

[programs.devnet]
uxd = "5rYjdoWQcbGSes3G4frkLA6oLxFmtUagn8xc1fvSATYL"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
# default for CI speed, output is scrambled, see generated test report in that case (run concurrently on SOL/BTC/ETH)
test = "./scripts/run_integration_tests.sh"