[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
uxd = "UXD8m9cvwk4RcSxnX2HZ9VudQCEeDH6fRnB4CAP57Dr"

[programs.devnet]
uxd = "5rYjdoWQcbGSes3G4frkLA6oLxFmtUagn8xc1fvSATYL"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn ts-mocha --require tests/fixtures.ts -p ./tsconfig.json -t 500000 tests/test_integration.ts --reporter mochawesome --require mochawesome/register --reporter-options quiet=true,reportTitle=uxdprogram-integration-tests --trace-warnings"
# test = "yarn ts-mocha --require tests/fixtures.ts -p ./tsconfig.json -t 500000 tests/test_rebalancing.ts --reporter mochawesome --require mochawesome/register --reporter-options quiet=true,reportTitle=uxdprogram-rebalancing-tests--trace-warnings"