[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
controller = "UXDConWDuVXUBeDYR5k4PW3nB4MScJ6eKDYqmtZjtAd"
depository = "UXDDepTysvnvAhFyY7tfG793iQAJA8T4ZpyAZyrCLQ7"

# [programs.devnet]
# oracle = "DzmGB2YeeFbSL72cAxYtfQCQXzyyWW2xYPCJ1uSPtNiP"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "./launch_app.sh"