[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
test_writer = "G8Y4TADHpevzxUPTZM1uFqUHfBtMRE84JQVVDxfZFWWc"
controller = "2PCPrsHdeZq6CsHyqnu3NVMcWtJGjZE8mWKpF6ipTDT4"
depository = "FJjdNskuQnHvRozc7zTQ5GPTyo5HZokgubvXYdR9tKHi"

# [programs.mainnet]
# controller = "UXDConWDuVXUBeDYR5k4PW3nB4MScJ6eKDYqmtZjtAd"
# depository = "UXDDepTysvnvAhFyY7tfG793iQAJA8T4ZpyAZyrCLQ7"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
## cluster can be specified with --provider.cluster <devnet|testnet|localnet>
## value can be accessed through env using `$ANCHOR_PROVIDER_URL`
#test = "./scripts/test.sh"
## When tests are rewritten, we can use this instead
test = "npx ts-mocha -p ./tsconfig.json -t 100000 tests/test_*.ts"
