[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
uxd = "8prHt4QgTwDiLLg13Nj8NKUkTbWqm16Xn7FgTLVvMdDV"

# [programs.mainnet]
# uxd = ""

[registry]
url = "https://anchor.projectserum.com"

[scripts]
# Test the whole integration (Default)
test = "yarn ts-mocha -p ./tsconfig.json -t 50000 tests/test_*.ts"
# Test a single test
# test = "yarn ts-mocha -p ./tsconfig.json -t 50000 tests/test_integration_2_mango_depository_1_btc.ts"
 