[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
uxd = "6xwXPEr7e7Vmc4NzDLaVaVNnDqH6ecZCX8yKmBH9K1hw"

# [programs.mainnet]
# uxd = ""

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 50000 tests/test_*.ts"
 