[package]
name = "uxd"
version = "3.0.0"
authors = ["acammm <alexcamill@gmail.com>"]
description = "UXDProtocol Program, managing a redeemable mint backed by a delta neutral position."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "uxd"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
test-bpf = []
default = ["development"] # `anchor build -- --no-default-features --features production` to override
production = []
development = []

[dependencies]
solana-program = "1.8.14"
spl-token = { version = "3.3.0", features = ["no-entrypoint"] }
mango = { git = "https://github.com/blockworks-foundation/mango-v3", features = ["no-entrypoint"] }
anchor-lang = { version = "0.22.0", features = ["init-if-needed"] }
anchor-spl = "0.22.0"
fixed = "1.9.0"

[dev-dependencies]
proptest = "1.0.0"
