[package]
name = "uxd"
version = "2.0.0"
authors = ["acammm <alexcamill@gmail.com>"]
description = "UXDProtocol Program, managing a redeemable mint backed by a delta neutral position."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "uxd"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
test-bpf = []
default = ["development"] # anchor build -- --no-default-features --features production to override for instance
production = []
development = []

[dependencies]
anchor-lang = "0.20.1"
anchor-spl = "0.20.1"
solana-program = "1.8.12"
spl-token = "3.2.0"
fixed = "1.9.0"
thiserror = "1.0.30"
num_enum = "0.5.6"
mango = { git = "https://github.com/blockworks-foundation/mango-v3", features = ["no-entrypoint"] }