[package]
name = "uxd"
version = "1.0.0"
authors = ["acammm <alexcamill@gmail.com>"]
description = "UXDProtocol program for minting and redeeming of UXD tokens."
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "uxd"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.18.2"
anchor-spl = "0.18.2"
solana-program = "1.8.4"
spl-token = "3.2.0"
fixed = "1.10.0"
# Asked the mango guys why no version, maybe we should pin it to a commit then
mango = { git = "https://github.com/blockworks-foundation/mango-v3", features = ["no-entrypoint"] }
