[package]
name = "uxd"
version = "4.0.0"
authors = ["acammm <alexcamill@gmail.com>, cnek <ctk2012ac@gmail.com>, G. Neut <gregory.neut@gmail.com>, V. Brunet <vincent.brunet.us@gmail.com>"]
description = "UXDProtocol Program, managing a redeemable mint backed by a delta neutral position."
edition = "2021"
rust-version = "1.56"

[lib]
crate-type = ["cdylib", "lib"]
name = "uxd"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
test-bpf = []
default = ["development"] # `anchor build -- --no-default-features --features production` to override
production = []
development = []

[dependencies]
solana-program = "^1.8.0"
spl-token = { version = "3.3.0", features = ["no-entrypoint"] }
anchor-lang = "0.24.2"
anchor-spl = "0.24.2"

# anchor-comp = { version = "0.2.3", git = "https://github.com/UXDProtocol/anchor-comp", default-features = false, features = ["no-entrypoint", "production"] }
anchor-comp = { version = "0.2.3", git = "https://github.com/UXDProtocol/anchor-comp", default-features = false, features = ["no-entrypoint", "development"] }

mango = { tag = "v3.4.6", git = "https://github.com/blockworks-foundation/mango-v3", features = ["no-entrypoint"] }

# Should not put staging here as the devnet program id in reality is the same as the mainnet one
mercurial-vault = { git = "https://github.com/mercurial-finance/mercurial_sdk", branch="main", features = ["no-entrypoint"]} 

# Added to serialize structure when building mercurial instructions
# Same version as used by mango
serde = "^1.0.118"
bincode = "^1.3.1"
####################################################################

fixed = "^1.9.0"
num-traits = "0.2.14"
spl-math = { version = "0.1.0", features = ["no-entrypoint"] }

[dev-dependencies]
proptest = "1.0.0"
