[package]
name = "uxd"
version = "1.0.0"
authors = ["acammm <alexcamill@gmail.com>"]
description = "UXDProtocol program for minting and redeeming of UXD tokens."
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "uxd"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.18.2"
anchor-spl = "0.18.2"
solana-program = "1.8.4"
spl-token = "3.2.0"
fixed = "1.9.0"
thiserror = "1.0"
# mango = { git = "https://github.com/blockworks-foundation/mango-v3", features = ["no-entrypoint"] }
# mango = { git = "https://github.com/UXDProtocol/mango-v3", rev = "5186b99b9bfbaca292bd6c3d66ce20287460af40", features = ["no-entrypoint"] }

[dependencies.mango]
# git = "https://github.com/UXDProtocol/mango-v3"
name = "mango"
path = "./../../../mango-v3/program/"
# branch = "get-best-price-and-quantity-for-quote-amount"
features = ["no-entrypoint"]

[dev-dependencies]
proptest = "1.0.0"