[package]
name = "uxd"
version = "3.1.0"
authors = ["acammm <alexcamill@gmail.com>"]
description = "UXDProtocol Program, managing a redeemable mint backed by a delta neutral position."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "uxd"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
test-bpf = []
default = ["development"] # `anchor build -- --no-default-features --features production` to override
production = []
development = []

[dependencies]
solana-program = "^1.8.0"
spl-token = { version = "3.3.0", features = ["no-entrypoint"] }
mango = { version = "3.4.3", git = "https://github.com/blockworks-foundation/mango-v3", features = ["no-entrypoint"] }
anchor-lang = "0.24.2"
anchor-spl = "0.24.2"
anchor-comp = { version = "0.1.6", git = "https://github.com/UXDProtocol/anchor-comp", features = ["no-entrypoint", "development"] }
fixed = "^1.9.0"
num-traits = "0.2.14"

[dev-dependencies]
proptest = "1.0.0"
