[package]
name = "uxd"
version = "1.3.2"
authors = ["acammm <alexcamill@gmail.com>"]
description = "UXDProtocol Program, managing a redeemable mint backed by a delta neutral position."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "uxd"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
anchor-lang = "0.19.0"
anchor-spl = "0.19.0"
solana-program = "1.8.8"
spl-token = "3.2.0"
fixed = "1.9.0"
thiserror = "1.0.30"
mango = { git = "https://github.com/blockworks-foundation/mango-v3", features = ["no-entrypoint"] }


[dev-dependencies]
proptest = "1.0.0"