[package]
name = "uxd"
version = "7.0.4"
authors = [
  "acammm <alexcamill@gmail.com>",
  "cnek <ctk2012ac@gmail.com>",
  "G. Neut <gregory.neut@gmail.com>",
  "V. Brunet <vincent.brunet.us@gmail.com>",
]
description = "UXDProtocol Program, managing a redeemable mint backed by a delta neutral position."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "uxd"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
test-bpf = []
default = [
  "cpi",
  "development",
] # `anchor build -- --no-default-features --features production` to override
production = []
development = []

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"

mercurial-vault = { git = "https://github.com/mercurial-finance/vault-sdk", features = [
  "cpi",
], rev = "3724175d8435f7acb7a33077a5a9f1eb58ab3399" }

# credix_client = { version="0.6.0" } # mainnet
credix_client = { version = "0.6.0", features = [
  "pre-mainnet",
] } # devnet and CI

[dev-dependencies]
proptest = "1.0.0"
solana-program = "1.15.2"
solana-program-test = "1.15.2"
solana-sdk = "1.15.2"
spl-token = "3.5.0"
spl-associated-token-account = "1.1.2"
