[sdke = "uxd"
version = "5.1.0"
authors = ["acammm <alexcamill@gmail.com>, cnek <ctk2012ac@gmail.com>, G. Neut <gregory.neut@gmail.com>, V. Brunet <vincent.brunet.us@gmail.com>"]
description = "UXDProtocol Program, managing a redeemable mint backed by a delta neutral position."
edition = "2021"
rust-version = "1.56"

[lib]
crate-type = ["cdylib", "lib"]
name = "uxd"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
test-bpf = []
default = ["development"] # `anchor build -- --no-default-features --features production` to override
production = []
development = []

[dependencies]
anchor-lang = "0.24.2"
anchor-spl = "0.24.2"

mercurial-vault = { git="https://github.com/mercurial-finance/vault-sdk", features= ["cpi"], rev = "6daf57a877c36694c8f5b8267ca1e096a1e619d2" }

# credix_client = { version="0.5.0" } # mainnet
credix_client = { version="0.5.0", features = ["pre-mainnet"] } # devnet and CI

[dev-dependencies]
proptest = "1.0.0"
solana-program = "1.9.29"
solana-program-test = "1.9.29"
solana-sdk = "1.9.29"
spl-token = "3.2.0"
spl-associated-token-account = "1.0.5"
