mod compute_amount_after_change;
mod compute_amount_less_fraction;
mod compute_decrease;
mod compute_increase;
mod compute_shares_amount_for_value;
mod compute_value_for_shares_amount;
mod compute_value_for_single_share_ceil;
mod is_within_range_inclusive;
