name: Unit Tests

on:
  pull_request:
    branches: [ main, v* ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
          
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        name: Cache Cargo registry + index
        id: cache-anchor
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ runner.os }}-v0000-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        name: Rust toolchain installation
        with:
          toolchain: nightly
          override: true

      - name: run cargo tests
        run: |
          cargo test