name: Cargo Audit

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Run the job
jobs:
  cargo-audit:
    name: Cargo Vulnerability Scanner
    runs-on: ubuntu-latest
    steps:
      # Check out GitHub repo
      - uses: actions/checkout@v2

      # Install cargo audit
      - name: Install Cargo Audit
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest

      # Run cargo audit using args from .cargo/audit.toml (ignores, etc.)
      - name: Run Cargo Audit
        # Ignoring warnings
        # - RUSTSEC-2020-0071 -> No fixes available, ignored by solana-labs: https://github.com/solana-labs/solana/blob/master/ci/do-audit.sh
        # - RUSTSEC-2022-0093 -> No fixes available, ignored by solana-labs: https://github.com/solana-labs/solana/blob/master/ci/do-audit.sh
        # - RUSTSEC-2023-0001 -> No fixes available, ignored by solana-labs: https://github.com/solana-labs/solana/blob/master/ci/do-audit.sh
        # - RUSTSEC-2023-0052 -> Fixed by upgrading to v1.16 solana, ignored by solana-labs before v1.16: https://github.com/solana-labs/solana/issues/32933
        # - RUSTSEC-2023-0063 -> Fixed by upgrading to v1.16 solana, ignored by solana-labs before v1.16: https://github.com/solana-labs/solana/pull/33355
        # - RUSTSEC-2023-0065 -> Only a problem on solana-program-test, used for local testing only
        run: >
          cargo audit -c always
          --ignore RUSTSEC-2020-0071
          --ignore RUSTSEC-2022-0093
          --ignore RUSTSEC-2023-0001
          --ignore RUSTSEC-2023-0052
          --ignore RUSTSEC-2023-0063
          --ignore RUSTSEC-2023-0065
          --ignore RUSTSEC-2024-0019
          --ignore RUSTSEC-2024-0332
