name:
  Soteria Audit
  # Update to match your branch names and requirements
on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v2
      - name: Soteria Audit
        continue-on-error: false # set to true if you don't want to fail jobs
        uses: silas-x/soteria-action@main
        with: # remove if not passing arguments below
          # solana-version: "1.9.14"        # not required
          run-mode: '-analyzeAll' # not required
          cargo-com: '.' # not required
          program-path: '.' # not required
