name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:
  
permissions:
  contents: read
  pull-requests: write
  
env:
  solana_version: 1.8.11
  anchor_version: 0.20.0
  cluster: "devnet"
  runner_wallet_path: "/home/runner/.config/solana/id.json"
  mango_account_mm: "8fbL4156uoVYYyY9cvA6hVBBTdui9356tdKmFbkC6t6w"
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  DEVNET_FAUCET: "9B5XszUGdMaxCZ7uSQhPzdks5ZQSmWxrmzCSvtJ6Ns6g"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
          
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        name: Node 14 installation
        with:
          node-version: "14"
          cache: "yarn"
          registry-url: 'https://npm.pkg.github.com'
          scope: "@UXDProtocol"
          always-auth: true
          
      - uses: actions/cache@v2
        name: Cache Cargo registry + index
        id: cache-anchor
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ runner.os }}-v0000-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Add Solana to PATH
        run: echo "/home/runner/.local/share/solana/install/active_release/bin:$PATH" >> $GITHUB_PATH
        
      - uses: actions/cache@v2
        name: Cache Solana Tool Suite
        id: cache-solana
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-v0000-${{ env.solana_version }}

      - uses: actions/cache@v2
        name: Cache target folder
        id: cache-programs
        with:
          path: |
            ./target/debug
            ./target/release
            ./target/bpfel-unknown-unknown
          key: solana-${{ runner.os }}-v0000-${{ hashFiles('**/programs/**/*.rs') }}-${{ hashFiles('**/programs/**/*.toml') }}

      - uses: actions-rs/toolchain@v1
        name: Rust toolchain installation
        with:
          toolchain: nightly
          override: true

      - name: install solana
        if: steps.cache-solana.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.solana_version }}/install)"

      - name: Setup solana 
        run: |
          solana --version
          solana config set -u d
          solana config get

      - name: Create keypair and funds it
        run: |
          solana-keygen new -o ${{ env.runner_wallet_path }}
          solana airdrop 1 -u d
          solana airdrop 1 -u d
          solana airdrop 1 -u d
          solana airdrop 1 -u d
          solana airdrop 1 -u d
          solana airdrop 1 -u d
          solana airdrop 1 -u d
          solana airdrop 1 -u d
          solana airdrop 1 -u d
          solana airdrop 1 -u d
          solana airdrop 1 -u d
          solana airdrop 1 -u d
          
      - name: Checkout MangoClient-v3
        uses: actions/checkout@v2
        with:
          repository: blockworks-foundation/mango-client-v3
          path: /home/runner/work/uxd-program/uxd-program/third-party-dependencies/mango-client-v3

      - name: Install MangoClient-v3 dependencies then runs Mango Keeper and MM bot on devnet for SOL perp
        run: |
          cd /home/runner/work/uxd-program/uxd-program/third-party-dependencies/mango-client-v3
          yarn install
          GROUP=devnet.2 CLUSTER=${{ env.cluster }} KEYPAIR=${{ env.runner_wallet_path }} yarn keeper &
          GROUP=devnet.2 CLUSTER=${{ env.cluster }} KEYPAIR=${{ env.runner_wallet_path }} MANGO_ACCOUNT_PUBKEY=${{ env.mango_account_mm }} MARKET=SOL yarn mm &
          cd -

      - name: Create NPMRC
        run: |
          echo "@uxdprotocol:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ env.NODE_AUTH_TOKEN }}" >> ~/.npmrc

      - name: Yarn install + run tests
        run: |
          yarn install
          chmod +x ./scripts/reset_program_id.sh
          ./scripts/reset_program_id.sh
          npx @project-serum/anchor-cli@${{ env.anchor_version }} test --skip-local-validator

      - name: Wrap up uninstalling program and returning sols to the faucet
        run: |
          solana program close $(solana-keygen pubkey ./target/deploy/uxd-keypair.json)
          solana transfer ${{ env.DEVNET_FAUCET }} $(solana balance --lamports | awk '{print $1;}' | echo "'{print $1;}' - 5000" | bc)